name: Test parse_modem_status.py Dev

on:
  push:
    branches:
      - dev
    paths:
      - 'src/*'

jobs:
  test_dev:
    name: Test dev
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v4
      with:
        ref: 'dev'
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/requirements.txt
    - name: Setup NGINX
      uses: nyurik/action-setup-nginx@v1.1
